import React from 'react';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

const Privacy = () => (
    <div className="min-h-screen">
      <Header />
    <div className="container mx-auto px-4 py-12 max-w-3xl">
      <h1 className="text-4xl font-bold mb-6 text-deep-bottle-green">Privacy Policy</h1>
      <p className="mb-2 text-sm text-gray-500">Effective Date: 22 June, 2025</p>
      <p className="mb-8 text-sm text-gray-500">Website: www.bookmyayurveda.com</p>
      <h2 className="text-2xl font-semibold mt-8 mb-2">1. Introduction</h2>
      <p className="mb-4">At BookMyAyurveda, we recognize the importance of protecting your personal information and are committed to maintaining your privacy. This Privacy Policy outlines in detail how we collect, use, store, and protect any information you provide while accessing our website and services. By using this website, you acknowledge that you have read, understood, and accepted the practices described in this policy, and you consent to the collection and use of your information in accordance with this policy.</p>
      <h2 className="text-2xl font-semibold mt-8 mb-2">2. No User Login or Registration</h2>
      <p className="mb-4">We understand and respect the need for privacy when seeking wellness and health-related information. Accordingly, BookMyAyurveda does not require you to create an account, register, or log in to access the information provided on our website or to book a consultation. Any interaction with our platform is entirely voluntary and anonymous unless you decide to provide personal details for the purpose of booking a consultation or seeking further assistance. This approach ensures that you have complete control over the information you choose to share with us.</p>
      <h2 className="text-2xl font-semibold mt-8 mb-2">3. Information Collection</h2>
      <p className="mb-4">While using our website, you may choose to share certain personal information to enable us to provide our services effectively. This information may include your name, email address, and contact number, which are necessary to coordinate consultations and communicate with you. Additionally, you may voluntarily provide health-related information or describe your symptoms in connection with your consultation requests. We may also collect limited browser or device-related information through cookies and similar technologies to enhance website performance, analyze usage trends, and improve the overall user experience. It is important to note that we do not collect sensitive financial information such as credit card details, banking information, or passwords directly through our website.</p>
      <h2 className="text-2xl font-semibold mt-8 mb-2">4. Use of Information</h2>
      <p className="mb-4">The information you provide is used strictly for the purpose of facilitating Ayurvedic consultations, responding to your queries, and delivering the services you have requested. We may also use your information to improve the quality and functionality of our website, enhance your experience as a user, and ensure that our content and services are relevant and helpful. Under no circumstances do we sell, rent, or trade your personal information with any third party. We are committed to using your data solely for the purpose of providing you with our services and improving our platform.</p>
      <h2 className="text-2xl font-semibold mt-8 mb-2">5. Ayurvedic Consultation — User Consent, Disclaimer, and Acknowledgment</h2>
      <p className="mb-4">BookMyAyurveda provides Ayurvedic consultations strictly based on classical Indian health traditions and principles. All consultations are conducted by qualified Ayurvedic practitioners located in India. It is essential to understand that Ayurveda is recognized as a traditional wellness system in India but may not be recognized as a licensed medical practice in other countries, including the United States. We do not hold any certifications, accreditations, or regulatory approvals from any United States government agency or medical authority. By choosing to use our platform and seeking consultation, you acknowledge that you are voluntarily engaging with our services and that you fully understand the nature and scope of our offerings. You agree that you are solely responsible for seeking this consultation and that you are doing so of your own free will and at your own risk. We strongly recommend that you consult a licensed healthcare provider or physician in your country before making any medical decisions based on the information or advice received from our Ayurvedic practitioners. Our services and consultations are provided on an as-is basis, without any warranties, guarantees, or representations, either express or implied, regarding the accuracy, completeness, or suitability of the information provided. By using our services, you expressly release BookMyAyurveda and its practitioners from any liability arising from the use or misuse of the information provided during consultations.</p>
      <h2 className="text-2xl font-semibold mt-8 mb-2">6. Data Security</h2>
      <p className="mb-4">We take reasonable technical and organizational measures to protect the personal information you share with us. These measures are designed to prevent unauthorized access, alteration, disclosure, or destruction of your information. Despite our best efforts, please be aware that no internet-based platform can guarantee absolute security. Therefore, while we strive to protect your personal data, you acknowledge that you provide your information at your own risk.</p>
      <h2 className="text-2xl font-semibold mt-8 mb-2">7. Cookies</h2>
      <p className="mb-4">Our website may utilize cookies and similar tracking technologies to enhance your browsing experience and to help us understand how users interact with our website. Cookies allow us to recognize your browser, remember your preferences, and improve the overall functionality of our services. You can adjust your browser settings at any time to disable cookies if you prefer not to accept them. However, disabling cookies may affect the usability and functionality of certain features of our website.</p>
      <h2 className="text-2xl font-semibold mt-8 mb-2">8. Third-Party Links</h2>
      <p className="mb-4">For your convenience, our website may contain links to third-party websites that we believe may be relevant or helpful to you. These external websites operate independently and have their own privacy policies and terms of use. We do not have control over and are not responsible for the content, practices, or privacy policies of these third-party sites. We encourage you to review their privacy policies before sharing any personal information with them.</p>
      <h2 className="text-2xl font-semibold mt-8 mb-2">9. Changes to This Policy</h2>
      <p className="mb-4">We reserve the right to modify or update this Privacy Policy at any time to reflect changes in our practices, technology, or legal requirements. Any updates or modifications will be posted on this page with an updated effective date. We encourage you to periodically review this policy to stay informed about how we are protecting your information and maintaining your privacy.</p>
      <h2 className="text-2xl font-semibold mt-8 mb-2">10. Contact Us</h2>
      <p className="mb-4">If you have any questions, concerns, or requests regarding this Privacy Policy or the way we handle your personal information, please feel free to contact us at <a href="mailto:support@bookmyayurveda.com" className="text-pea-green underline">support@bookmyayurveda.com</a> or call us at <a href="tel:+18885118535" className="text-pea-green underline">+1 888 511 8535</a>. We are committed to addressing your inquiries promptly and ensuring that your privacy and trust are maintained at all times.</p>
      </div>
      <Footer />
    </div>
  );

export default Privacy;
